### ISSUE TITLE
Color changes needed for the visa map

### ISSUE THREAD

**Issue by psabev** [suricactus/mfa_travel#1]
The difference between "green"and "darkgreen" is very small and makes it hard to distinguish on the map.
I would recommend:
1. Set darkgreen for "no visa needed".
2. Set teal or something more distinguishing for "no visa needed, enter with id".
3. Do not use green, as the color is too close to darkgreen.

**Comment by suricactus** [comment]
I agree the colors are really close to each other. On the other hand, traveling with or without ID card is not the purpose of the map, the main focus is of MFA recommendation and need of visa to travel. I changed the colors a bit, now for European countries I use teal and changed red to orange, because it was too bright.
